name: mobile
description: "App móvil (Android) de la plataforma de Proyectos Integradores UPB."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0                 # llamadas REST al backend Express
  provider: ^6.1.5             # estado de sesión compartido
  shared_preferences: ^2.5.3   # persistencia local del JWT
  file_picker: ^13.0.0          # elegir archivos para subir a una versión

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true